---

env:
  - distribution: 'centos'
    version: 7
    run_opts: '--privileged --volume="/sys/fs/cgroup:/sys/fs/cgroup:ro"'
    init: '/usr/lib/systemd/systemd'
  - distribution: 'ubuntu'
    version: 14.04
    run_opts: ''
    init: '/sbin/init'
  - distribution: 'ubuntu'
    version: 16.04
    run_opts: '--privileged --volume="/sys/fs/cgroup:/sys/fs/cgroup:ro"'
    init: '/lib/systemd/systemd'

language: 'python'

python:
  - '2.7'

services:
  - 'docker'

sudo: 'required'


before_install:
  - >-
    docker build
    --file=tests/Dockerfile.${distribution}-${version}
    --tag=${distribution}-${version}:ansible
    tests

  - >-
    docker run
    --detach
    --env="ANSIBLE_FORCE_COLOR=true"
    --env="ANSIBLE_LOG_PATH=/var/log/ansible.log"
    --name="container"
    --volume="${PWD}:/etc/ansible/roles/openstack-keystone:rw"
    ${run_opts} ${distribution}-${version}:ansible "${init}"

install:
  - 'pip install -r requirements-devel.txt'

script:
  - 'yamllint -c .yamllint.conf .'

  # Ansible syntax check.
  - >-
    docker exec container ansible-playbook
    /etc/ansible/roles/openstack-keystone/tests/test.yml --syntax-check

  # Test role.
  - >-
    docker exec container ansible-playbook
    /etc/ansible/roles/openstack-keystone/tests/test.yml --diff --verbose

  # Test role idempotence.
  - >-
    docker exec container ansible-playbook
    /etc/ansible/roles/openstack-keystone/tests/test.yml --diff --verbose

  - >-
    docker exec container
    tail -n 1 /var/log/ansible.log | grep -q "changed=0  *unreachable=0  *failed=0"
